---
fullname: Record Update
shortname: coq-record-update
opam_name: coq-record-update
organization: tchajed
action: true
community: false
coqdoc: false

synopsis: >-
  Generic support for updating record fields in Coq

description: |-
  While Coq provides projections for each field of a record, it has no
  convenient way to update a single field of a record. This library provides a
  generic way to update a field by name, where the user only has to implement a
  simple typeclass that lists out the record fields.

authors:
- name: Tej Chajed
  initial: true

maintainers:
- name: Tej Chajed
  nickname: tchajed

opam-file-maintainer: tchajed@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.14 or later
  opam: '{(>= "8.14" & < "8.20~") | (= "dev")}'

tested_coq_opam_versions:
- version: dev
- version: '8.19'
- version: '8.18'
- version: '8.17'
- version: '8.15'
- version: '8.14'

namespace: RecordUpdate

keywords:
- name: record

categories:
- name: Computer Science/Data Types and Data Structures
---
